### PR TITLE
Fix for  usg 4.4.22

### PR DESCRIPTION
**Pull request by dkanbier**
Using the latest stable firmware on USG and controller broke my configuration. These changes where required to get KPN IPTV working on version:

Controller: 5.8.24
USG firmware: 4.4.22.5086045

### CODE REVIEW

**Comment by slootjes** [comment]
Thanks for this, will try. Hopefully it will be merged but my PR from december last year is also not merges yet...

**Comment by dkanbier** [comment]
@slootjes let me know if you need any help. I needed to change a couple of other things to get KPN IPTV working with the latest firmware but they where unrelated to this repository.

**Comment by slootjes** [comment]
What things? Maybe others will run into it too.

**Comment by dkanbier** [comment]
Actually there is one thing left. I had static dhcp bindings configured in my config.gateway.json which  caused the USG to get into a provisioning loop.  Found the cause and fixed it, shared with the community here: 

https://community.ubnt.com/t5/UniFi-Routing-Switching/USG-Pro-4-4-21-config-gateway-json/m-p/2355435/highlight/true#M90659

**Review by eenbrauw — APPROVED** [review]

**Comment by basmeerman** [comment]
Thanks for the contributions.

**Pull request merged**
